#! /bin/sh

#
# Check invalid IA32 VTOP translation.
#

pf="-p ia32:12,10,10"
ptes="-e 0x234:0x4000e7"
list="0x123456789"

totalrc=0
for tst in $list; do
    input="${tst%:*}"
    expect="${tst#*:}"
    echo -n "Checking $input... "
    output=$( ./addrxlat $pf $ptes $input )
    rc=$?
    if [ $rc -gt 1 ]; then
        echo ERROR
        echo "Cannot translate $input" >&2
        exit $rc
    elif [ $rc -ne 1 ]; then
        echo FAILED
	echo "Expected error, got $output"
        totalrc=1
    else
        echo OK
    fi
done

exit $totalrc
