#! /bin/sh

#
# Check null-mapping VTOP translation.
#

pf="none:64"
ptes=
input="0x0 0x2 0x30 0x400 0x5000 0x123456789abcdef"
list=
for addr in $input; do
    list="$list $addr:$addr"
done

. "$srcdir"/addrxlat-common
