#! /bin/sh

#
# Check invalid IA32 PAE VTOP translation.
#

pf="-p ia32_pae:12,9,9,2"
ptes="-e 0x0:0x1067 -e 0x18d0:0x2000e7"
list="0x123456789"

totalrc=0
for tst in $list; do
    input="${tst%:*}"
    expect="${tst#*:}"
    echo -n "Checking $input... "
    output=$( ./addrxlat $pf $ptes $input )
    rc=$?
    if [ $rc -gt 1 ]; then
        echo ERROR
        echo "Cannot translate $input" >&2
        exit $rc
    elif [ $rc -ne 1 ]; then
        echo FAILED
	echo "Expected error, got $output"
        totalrc=1
    else
        echo OK
    fi
done

exit $totalrc
