#! /bin/sh

#
# Check invalid VTOP translation for s390x with 2-level paging.
#

pf="-p s390x:12,8,11"

ptes="-e 0x0000:0x1000"		# SX0

list="0x20000000000000"		# non-zero RFX
list="$list 0x40000000000"	# non-zero RSX
list="$list 0x80000000"		# non-zero RTX

. "$srcdir"/addrxlat-invalid
