#! /bin/sh

#
# Create a diskdump file with VMCOREINFO data. The corresponding header field
# was added in v3 and superseded by ELF notes in v4, so the version is forced
# to v3 here.
#

pageflags=raw
extraparam="
version = 3
VMCOREINFO = vmcoreinfo.data
"
extracheckattr="
linux.vmcoreinfo.lines.OSRELEASE = string:6.4.3-1-default
linux.vmcoreinfo.lines.PAGESIZE = string:4096
linux.vmcoreinfo.lines.CRASHTIME = string:1689103980
"
. "$srcdir"/diskdump-basic
exit 0
