#! /bin/sh

#
# elf-empty-i386
#
# Create an empty ELF dump file and verify meta-attributes.
#

arch=ia32
byte_order=1
ptr_size=4
page_shift=12
page_size=4096
pteval_spec=nil

ei_class=1
ei_data=1
e_machine=3

. "$srcdir"/elf-empty
