#! /bin/sh

#
# elf-empty-ppc64
#
# Create an empty dump file and verify meta-attributes.
#

arch=ppc64
byte_order=0
ptr_size=8
pteval_spec="number: 8"

ei_class=2
ei_data=2
e_machine=21

. "$srcdir"/elf-empty
