#! /bin/sh

#
# elf-empty-aarch64
#
# Create an empty dump file and verify meta-attributes.
#

arch=aarch64
byte_order=1
ptr_size=8
pteval_spec="number: 8"

ei_class=2
ei_data=1
e_machine=183

. "$srcdir"/elf-empty
