#! /bin/sh

#
# lkcd-empty-x86_64
#
# Create an empty LKCDv9 dump file and verify meta-attributes.
#

arch=x86_64
byte_order=1
ptr_size=8
page_shift=12
page_size=4096
page_offset=0x0000010000000000

panic="Test panic string"
node=test-node
sysname=Linux
release=3.4.5-test
version="#1 SMP Fri Jan 22 14:02:42 UTC 2016 (1234567)"
machine=x86_64
domain="(none)"

. ./lkcd-empty
