#! /bin/sh

#
# Check Xen pre-3.2 X86_64 translation without explicit version,
# using page table content alone
#

opts=(
    arch=x86_64
    ostype=2
    rootpgt=MACHPHYSADDR:0xffc94000
)

. "$srcdir"/xlat-os-common
