#! /bin/bash

#
# Check Linux X86_64 translation where two Page Tables must
# be scanned to find the start/end
#

opts=(
    arch=x86_64
    ostype=linux
    phys_base=0
)

. "$srcdir"/xlat-os-common
